Gemfile
Gemfile.lock
app/controllers/pigeons_controller.rb
app/views/pigeons/show.html.erb
db/seeds.rb

- Add a seed of 10 pigeons with **faker** gem (think to bundle install) : id start by 2 because ID n°1 was delete for test.
- Add a delete button in the show page.

Update new pigeon

---

Gemfile.lock
app/views/pigeons/show.html.erb

I added price, color in index.html.erb

Pigieons index

---

Gemfile.lock
app/controllers/pigeons_controller.rb
app/views/layouts/application.html.erb
app/views/shared/_navbar.html.erb
db/seeds.rb

-added nav bar with links
@GorillaDunk

Navbar links

---

app/controllers/bookings_controller.rb
app/models/booking.rb
app/models/pigeon.rb
app/models/user.rb
config/routes.rb
db/migrate/20230530161840_create_bookings.rb
db/schema.rb
db/seeds.rb
test/controllers/bookings_controller_test.rb
test/models/booking_test.rb

Added booking model -> Made a change to define has_many relation
Added controller for booking
Added seed for booking
Added nested routes
@pablohennique

Added booking model, controller, seed

---

app/assets/stylesheets/components/_banner.scss
app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_card_trip.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_search_form.scss
app/assets/stylesheets/pages/_home.scss
app/controllers/pages_controller.rb
app/views/pages/home.html.erb
app/views/pigeons/_pigeon_card.html.erb
app/views/pigeons/_pigeons_list.html.erb
app/views/pigeons/index.html.erb

- add a banner to home page
- add cards
- add link to cards

Create home page

---

app/controllers/pages_controller.rb
app/views/pages/_banner.html.erb
app/views/pages/home.html.erb
app/views/pages/search.html.erb
config/routes.rb

- Add search on pages routes and pages controller
- Create a view for search controller
- Clean the home page html

Clean code from hp

---

app/controllers/pigeons_controller.rb
app/models/pigeon.rb
app/views/pigeons/edit.html.erb
app/views/pigeons/new.html.erb
app/views/pigeons/show.html.erb
db/migrate/20230530214324_add_city_to_pigeons.rb
db/schema.rb
db/seeds.rb

- added column and edited fields in forms

updated city column for pigeons

---

Gemfile
Gemfile.lock
app/controllers/pages_controller.rb
app/controllers/pigeons_controller.rb
app/models/pigeon.rb
app/views/pigeons/_form.html.erb
app/views/pigeons/edit.html.erb
app/views/pigeons/new.html.erb
app/views/pigeons/show.html.erb
config/environments/development.rb
config/storage.yml

- add upload file on edit and new form
- add search method on pages controller
- add gem cloundary (think to bundle instal)
- add cloundary key on .env
- add has_one_photo to model pigeon

add image from new and edit

---

app/controllers/bookings_controller.rb
app/views/bookings/_booking_card_buyer.html.erb
app/views/bookings/_booking_card_seller.html.erb
app/views/bookings/_booking_list.html.erb

I added booking controller and model and implemented to see bookings as a buyer and seller

booking lists based on buyer's perspective and seller's perspective

---

Gemfile
app/controllers/bookings_controller.rb
app/views/bookings/_booking_card_buyer.html.erb
app/views/bookings/_booking_card_seller.html.erb
app/views/bookings/_form.html.erb
app/views/pigeons/show.html.erb
db/migrate/20230601032238_add_column_to_booking.rb
db/migrate/20230601032916_change_column_name_in_booking.rb
db/migrate/20230601032942_change_column_type_in_booking.rb
db/schema.rb

migration
fixed pigeon user on off
added calendar

migration, fixed pigeon user on or off, added calendar

---

app/controllers/pages_controller.rb
db/seeds.rb

fixed search with coordinates

---

app/views/pigeons/_pigeon_card.html.erb
app/views/pigeons/_pigeons_list.html.erb
db/seeds.rb

added images for pigeons card
fixed seed to work with random images
removed avatar from card 
fixed / day
centered grid
@GorillaDunk

Improve pigeon card

---

app/views/pigeons/my_pigeons.html.erb
app/views/pigeons/show.html.erb

btns solved

---

app/assets/stylesheets/components/_avatar.scss
app/assets/stylesheets/components/_card_trip.scss
app/views/bookings/_booking_card_buyer.html.erb
app/views/bookings/_booking_card_seller.html.erb
app/views/bookings/index.html.erb
app/views/bookings/rent_from.html.erb
app/views/bookings/rent_to.html.erb

fixed booking grids
fixed seed issue

Pretty login

---

app/assets/stylesheets/components/_card_category.scss
app/assets/stylesheets/components/_card_trip.scss
app/assets/stylesheets/components/_index.scss
app/javascript/controllers/booking_controller.js
app/javascript/controllers/index.js
app/views/bookings/index.html.erb
app/views/pigeons/my_pigeons.html.erb

added two features
one for the booking
one for the pigeon card

Booking page

---

app/views/shared/_footer.html.erb

Improve footer

---

app/views/pigeons/show.html.erb

- just delete the "Send a message text" on show page because we don't have time

Delete message pigeon show

---

app/javascript/controllers/index.js
app/javascript/controllers/move_booking_controller.js
app/views/bookings/_booking_card_seller.html.erb
app/views/bookings/rent_to.html.erb
app/views/shared/_footer.html.erb

implemented js action to move card, but its not the way to do it
other minor changes

Bookings js

---

app/assets/stylesheets/components/_card_trip.scss
app/views/pigeons/_pigeon_card.html.erb

the letter on the card fixed

---

app/assets/stylesheets/components/_card_trip.scss
app/controllers/bookings_controller.rb
app/views/bookings/rent_from.html.erb
app/views/bookings/rent_to.html.erb
app/views/pigeons/_my_pigeon_card.html.erb
app/views/pigeons/edit.html.erb
app/views/pigeons/my_pigeons.html.erb
db/schema.rb

- change path after booked a pigeon
- improve my pigeons list

Improve booking path

---

app/assets/stylesheets/components/_card_trip.scss
app/views/pigeons/_pigeon_card.html.erb

photo fixed

---

app/assets/stylesheets/components/_card_trip.scss
app/views/pigeons/_my_pigeon_card.html.erb
app/views/pigeons/my_pigeons.html.erb
db/schema.rb

my pigeon solved
